# Generated by Django 6.0.3 on 2026-04-26 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_FileResource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('image', '画像'), ('video', '動画'), ('pdf', 'PDF'), ('other', 'その他')], db_column='file_type', db_comment='ファイル種別', default='other', max_length=20, verbose_name='ファイル種別')),
                ('file_data', models.FileField(blank=True, db_column='file_data', db_comment='ファイルデータ', null=True, upload_to='file_resource/%Y/%m/%d/', verbose_name='ファイルデータ')),
                ('external_url', models.URLField(blank=True, db_column='external_url', db_comment='外部URL', max_length=512, null=True, verbose_name='外部URL')),
                ('file_name', models.CharField(db_column='file_name', db_comment='ファイル名', max_length=255, verbose_name='ファイル名')),
                ('file_size', models.BigIntegerField(blank=True, db_column='file_size', db_comment='ファイルサイズ', help_text='単位: Byte', null=True, verbose_name='ファイルサイズ')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'ファイルリソーストラン',
                'verbose_name_plural': 'ファイルリソーストラン',
                'db_table': 't_file_resource',
                'db_table_comment': 'ファイルリソーストラン',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('external_url__isnull', False)), fields=('external_url',), name='unique_t_file_resource_external_url_active')],
            },
        ),
    ]
