# Generated by Django 6.0.3 on 2026-04-29 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_fileresource',
            name='file_data',
        ),
        migrations.AddField(
            model_name='t_fileresource',
            name='file',
            field=models.FileField(blank=True, db_column='file', db_comment='ファイル', max_length=255, null=True, upload_to='file_resource/%Y/%m/%d/', verbose_name='ファイル'),
        ),
        migrations.AddConstraint(
            model_name='t_fileresource',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('file__isnull', False)), fields=('file',), name='unique_t_file_resource_file_active'),
        ),
    ]
