# Generated by Django 6.0.3 on 2026-05-03 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_t_fileresource_file_data_t_fileresource_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Emoji',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='code', db_comment='絵文字コード', max_length=50, verbose_name='絵文字コード')),
                ('display_name', models.CharField(blank=True, db_column='display_name', db_comment='表示名', max_length=10, null=True, verbose_name='表示名')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '絵文字マスタ',
                'verbose_name_plural': '絵文字マスタ',
                'db_table': 'm_emoji',
                'db_table_comment': '絵文字マスタ',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_m_emoji_code_active')],
            },
        ),
        migrations.CreateModel(
            name='M_Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', db_comment='タグ名', max_length=64, verbose_name='タグ名')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'タグマスタ',
                'verbose_name_plural': 'タグマスタ',
                'db_table': 'm_tag',
                'db_table_comment': 'タグマスタ',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_m_tag_name_active')],
            },
        ),
    ]
