# Generated by Django 6.0.3 on 2026-05-03 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_m_emoji_m_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='R_ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('item_type', models.CharField(choices=[('LOG', 'ログ')], db_column='item_type', db_comment='アイテム種別', max_length=20, verbose_name='アイテム種別')),
                ('item_id', models.UUIDField(db_column='item_id', db_comment='アイテムID', verbose_name='アイテムID')),
            ],
            options={
                'verbose_name': 'アイテムタグリレーション',
                'verbose_name_plural': 'アイテムタグリレーション',
                'db_table': 'r_item_tag',
                'db_table_comment': 'アイテムタグリレーション',
            },
        ),
        migrations.RemoveConstraint(
            model_name='t_fileresource',
            name='unique_t_file_resource_external_url_active',
        ),
        migrations.AddField(
            model_name='r_itemtag',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='r_itemtag',
            name='tag',
            field=models.ForeignKey(db_column='tag_id', db_comment='タグ', on_delete=django.db.models.deletion.CASCADE, related_name='tag_%(class)s_set', to='common.m_tag', verbose_name='タグ'),
        ),
        migrations.AddField(
            model_name='r_itemtag',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.RemoveField(
            model_name='t_fileresource',
            name='external_url',
        ),
        migrations.AddConstraint(
            model_name='r_itemtag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('item_type', 'item_id', 'tag'), name='unique_r_item_tag_item_type_item_id_tag_active'),
        ),
    ]
