"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os, platform
from datetime import timedelta
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

import environ

# ==============================================================================
# 設定ファイル目次
# ==============================================================================
# 1. 基盤設定                               : シークレットキー、デバッグモード、アプリ名などの基本設定
# 2. セキュリティ設定                        : ALLOWED_HOSTS、クッキー設定、認証関連URLなどのセキュリティ設定
# 3. アプリケーション定義                     : INSTALLED_APPS、MIDDLEWARE、URLconfなどのアプリ定義
# 4. データベース定義、データベース認証方式    : データベース接続、カスタムユーザーモデル、パスワード検証ルール
# 5. テンプレート                            : テンプレートエンジンの設定、コンテキストプロセッサ
# 6. 言語設定、静的ファイル設定               : 国際化、静的ファイル (STATIC)、ユーザーアップロードファイル (MEDIA)
# 7. 外部サービス設定                        : Cloudinary, メール送信設定など外部サービス連携
# 8. ログ設定                               : ロガー、ハンドラ、フォーマット設定
# 9. REST FRAMEWORK設定                     : REST APIに関する設定(JWT/エラーハンドラ)
# ==============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))

# ==============================================================================
# 1. 基盤設定
# ==============================================================================
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
# 生成ツール：https://www.miniwebtool.com/django-secret-key-generator/
APP_NAME: str = "SampleApp"
SECRET_KEY: str = env("SECRET_KEY")
DEBUG: bool = env.bool("DEBUG")
FRONTEND_URL = env("FRONTEND_URL")
# Windows環境 かつ 開発モード時にリロード検知プロセス/サーバプロセス両方でログハンドラを起動する為、
# ログがローテーションされない問題の対策
if platform.system() == "Windows" and DEBUG:
    if os.environ.get("RUN_MAIN") != "true":
        LOGGING_CONFIG = None
        LOGGING = {}

# ==============================================================================
# 2. セキュリティ設定
# ==============================================================================
# 通信を受け入れるホスト一覧
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

# セッション/クッキー設定(HTTPS設定を想定しない場合はFalseのまま)
# ログイン有効期限（秒）
SESSION_COOKIE_AGE: int = 3600  # 1時間(60秒*60)

# ブラウザ側でJavaScriptからクッキーを触らせない（XSS対策として推奨）
SESSION_COOKIE_HTTPONLY = True  # セッションIDをJSから盗ませない（XSS対策）
CSRF_COOKIE_HTTPONLY = False    # REST APIでReact等から叩く場合はFalseである必要がある(Django Admin や SPA (React等) からのリクエストを通すため)

# ローカルでは False、本番(環境変数)では True になるように管理
SESSION_COOKIE_SECURE: bool = env.bool("SESSION_COOKIE_SECURE")  # セッションのCookieはhttps通信の時のみ運ばせるか(HTTPONLYとは別)
CSRF_COOKIE_SECURE: bool = env.bool("CSRF_COOKIE_SECURE")  # CSRFトークンのCookieはhttps通信の時のみ運ばせるか(HTTPONLYとは別)

# ロードバランサー（SupabaseのインフラやHeroku/AWS等）経由でHTTPS通信をする場合に必要
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# クリックジャッキング対策(AdminやDjangoテンプレートを使用する場合には必要/APIのみの場合は不要)
X_FRAME_OPTIONS = "DENY"

# 独自トークンの有効期限
TOKEN_EXPIRY_SECONDS = {
    "account_activation": int(os.environ.get("TOKEN_EXPIRY_USER_ACTIVATION_SECONDS", 86400)), # 24h(86400/3600)
    "password_reset": int(os.environ.get("TOKEN_EXPIRY_PASSWORD_RESET_SECONDS", 3600)),    # 1h(3600/3600)
    # ... 他のトークン種別も追加 ...
}

# ==============================================================================
# 3. アプリケーション定義
# ==============================================================================
INSTALLED_APPS = [
    # ----- 外部パッケージ(django.contrib.adminより上に書く条件あり) -----
    "simple_history",
    # ----- Django 標準 Apps -----
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites", # Siteフレームワークの有効化
    # ----- 外部パッケージ -----
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    # ----- プロジェクト固有 Apps -----
    # 1. 基盤/管理系
    "core",
    "apps.account",       # アカウント認証・プロフィール機能
    "apps.common",        # 共通機能
    "apps.api_key",       # APIキー機能
    "apps.log",           # ログ機能

    # ----- マイグレーション実行単位(依存関係) -----
    # python manage.py makemigrations account common api_key
    # python manage.py migrate
]
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",                     # APIではCORSは必須
    "core.middlewares.same_site_middleware.SameSiteMiddleware",  # 独自ミドルウェア(SameSiteMiddlewareはCSRF/SessionMiddlewareより前に配置)
    # Django 標準 Middleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",      # Adminを使用する場合は必要
    "django.middleware.locale.LocaleMiddleware",                 # マルチ言語対応(管理画面の日本語化に必須)
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middlewares.logging_middleware.LoggingMiddleware",      # アクセスログ設定ミドルウェア
]
ROOT_URLCONF = "config.urls"
# 特定のシステムチェック警告を非表示にする
# W004: USERNAME_FIELDがuniqueでないことに対する警告
SILENCED_SYSTEM_CHECKS = [
    "auth.W004",
    "auth.E003",  # USERNAME_FIELD が unique=True でないことに対するエラーを無視
]
SITE_ID = 1

# ==============================================================================
# 4. テンプレート
# ==============================================================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # "DIRS": [],  # 特殊な共通テンプレートがなければ空でOK(今回はunfoldを使用するので不要)
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ==============================================================================
# 5. データベース定義、データベース認証方式
# ==============================================================================
DATABASES = {
    "default": {
        "ENGINE": env("DB_ENGINE"),
        "NAME": BASE_DIR / env("DB_NAME"),
        "ATOMIC_REQUESTS": env.bool("ATOMIC_REQUESTS"),
        "CONN_MAX_AGE": env.int("CONN_MAX_AGE"),
    },
}
# ユーザー認証モデルの設定（ユーザーマスタ）
AUTH_USER_MODEL = "account.M_User"
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Djangoデフォルト/認証バックエンド
]
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ==============================================================================
# 6. 言語設定、静的ファイル設定
# ==============================================================================
# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = "ja"
TIME_ZONE = "Asia/Tokyo"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # デプロイ時に必要

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==============================================================================
# 7. 外部サービス設定(外部ストレージ、メール)
# ==============================================================================
# メール設定
EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_FROM = env("EMAIL_FROM")

# メディア関連設定
# MEDIA_ROOT: 物理的なパス(サーバーのHDD内)
# => Djangoがファイルをどこに保存し、どこから読み込むか(例: /home/user/project/media/)
# MEDIA_URL: URLのパス (ブラウザのURLバー)
# => ブラウザから見たとき、ファイルにアクセスするためのURL開始地点(例: /media/)
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = '/media/'

# ==============================================================================
# 8. ログ設定
# ==============================================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    # フォーマットの設定
    "formatters": {
        # APIアクセスログ
        "access": {
            "format": "[{asctime}] {levelname} {process:d} {thread:d} {message}",
            "style": "{",
        },
        # アプリケーションログ
        "application": {
            "format": "[{asctime}] {levelname} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    # ハンドラ設定
    "handlers": {
        "handler_access": {
            "level": "DEBUG",  # DEBUGレベル以下は出さない(全てのレベルを出力)
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{BASE_DIR}/logs/access/access.log",
            "formatter": "access",
            "encoding": "utf-8",
            "when": "MIDNIGHT",
            "backupCount": env.int("ACCESS_LOG_BACKUP_COUNT"),
        },
        "handler_application": {
            "level": "DEBUG",  # DEBUGレベル以下は出さない(全てのレベルを出力)
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{BASE_DIR}/logs/application/application.log",
            "formatter": "application",
            "encoding": "utf-8",
            "when": "MIDNIGHT",
            "backupCount": env.int("APPLICATION_LOG_BACKUP_COUNT"),
        },
    },
    # ロガー設定
    "loggers": {
        "logger_access": {
            "handlers": ["handler_access"],
            "level": "DEBUG",  # DEBUGレベル以下は出さない(全てのレベルを出力)
            "propagate": True,
        },
        "logger_application": {
            "handlers": ["handler_application"],
            "level": "DEBUG",  # DEBUGレベル以下は出さない(全てのレベルを出力)
            "propagate": True,
        },
    },
}

# ==============================================================================
# 9. REST FRAMEWORK 定義
# ==============================================================================
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # 基本は「認証済みのみ」
    ],
    # JWT認証処理
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",  # Adminログイン中のデバッグ用に残すと便利
    ),
    # ExceptionHandler(カスタムエラークラスは以下にて設定)
    "EXCEPTION_HANDLER": "core.exceptions.exception_handler.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_ACCESS_DAYS", 0)),
        minutes=int(os.getenv("JWT_ACCESS_MINUTES", 0)),
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_DAYS", 30))
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "email",
    "USER_ID_CLAIM": "email",
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}
