# Generated by Django 6.0.3 on 2026-04-29 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ApiKeyScope',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='code', db_comment='コード', max_length=50, verbose_name='コード')),
                ('name', models.CharField(db_column='name', db_comment='スコープ名', max_length=100, verbose_name='スコープ名')),
                ('description', models.TextField(blank=True, db_column='description', db_comment='詳細説明', null=True, verbose_name='詳細説明')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'APIキースコープマスタ',
                'verbose_name_plural': 'APIキースコープマスタ',
                'db_table': 'm_api_key_scope',
                'db_table_comment': 'APIキースコープマスタ',
            },
        ),
        migrations.CreateModel(
            name='R_ApiKeyScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('api_key_scope', models.ForeignKey(db_column='api_key_scope_id', db_comment='APIキースコープマスタ', on_delete=django.db.models.deletion.CASCADE, related_name='api_key_scope_r_api_key_scope_set', to='api_key.m_apikeyscope', verbose_name='APIキースコープマスタ')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'APIキースコープリレーション',
                'verbose_name_plural': 'APIキースコープリレーション',
                'db_table': 'r_api_key_scope',
                'db_table_comment': 'APIキースコープリレーション',
            },
        ),
        migrations.CreateModel(
            name='T_ApiKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', db_comment='キー名', max_length=100, verbose_name='キー名')),
                ('description', models.TextField(blank=True, db_column='description', db_comment='使用用途', null=True, verbose_name='使用用途')),
                ('client_key', models.CharField(db_column='client_key', db_comment='クライアントキー', max_length=64, verbose_name='クライアントキー')),
                ('hashed_secret', models.CharField(db_column='hashed_secret', db_comment='ハッシュ化シークレットキー', max_length=128, verbose_name='ハッシュ化シークレットキー')),
                ('is_active', models.BooleanField(db_column='is_active', db_comment='有効フラグ', db_default=True, default=True, verbose_name='有効フラグ')),
                ('expired_at', models.DateTimeField(db_column='expired_at', db_comment='トークン有効期限', verbose_name='トークン有効期限')),
                ('last_used_at', models.DateTimeField(blank=True, db_column='last_used_at', db_comment='最終使用日時', null=True, verbose_name='最終使用日時')),
                ('revoked_reason', models.TextField(blank=True, choices=[('ROTATION', 'キーのローテーション'), ('UNUSED', '不要になった'), ('SECURITY', 'セキュリティ上の懸念'), ('USER_REQUEST', 'ユーザからの依頼'), ('OTHER', 'その他')], db_column='revoked_reason', db_comment='無効化理由コード', max_length=50, null=True, verbose_name='無効化理由コード')),
                ('revoked_detail', models.TextField(blank=True, db_column='revoked_detail', db_comment='無効化理由/詳細', null=True, verbose_name='無効化理由/詳細')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('scopes', models.ManyToManyField(db_comment='スコープ', related_name='scopes_t_api_key_set', through='api_key.R_ApiKeyScope', to='api_key.m_apikeyscope', verbose_name='スコープ')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='ユーザマスタ', on_delete=django.db.models.deletion.CASCADE, related_name='user_t_api_key_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ')),
            ],
            options={
                'verbose_name': 'APIキー発行トラン',
                'verbose_name_plural': 'APIキー発行トラン',
                'db_table': 't_api_key',
                'db_table_comment': 'APIキー発行トラン',
            },
        ),
        migrations.AddField(
            model_name='r_apikeyscope',
            name='api_key',
            field=models.ForeignKey(db_column='api_key', db_comment='APIキー発行トラン', on_delete=django.db.models.deletion.CASCADE, related_name='log_r_api_key_scope_set', to='api_key.t_apikey', verbose_name='APIキー発行トラン'),
        ),
        migrations.AddConstraint(
            model_name='m_apikeyscope',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_m_api_key_scope_code_active'),
        ),
        migrations.AddConstraint(
            model_name='t_apikey',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client_key',), name='unique_t_api_key_client_key_active'),
        ),
        migrations.AddConstraint(
            model_name='t_apikey',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'user'), name='unique_t_api_key_name_user_active'),
        ),
        migrations.AddConstraint(
            model_name='r_apikeyscope',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('api_key', 'api_key_scope'), name='unique_r_api_key_scope_api_key_api_key_scope_active'),
        ),
    ]
