# Generated by Django 6.0.3 on 2026-04-26 18:06

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_column='email', db_comment='メールアドレス', max_length=254, verbose_name='メールアドレス')),
                ('password', models.CharField(db_column='password', db_comment='パスワード', max_length=128, verbose_name='パスワード')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', db_comment='最終ログイン', null=True, verbose_name='最終ログイン')),
                ('is_active', models.BooleanField(db_column='is_active', db_comment='有効フラグ', db_default=False, default=False, verbose_name='有効フラグ')),
                ('is_staff', models.BooleanField(db_column='is_staff', db_comment='一般ユーザフラグ', db_default=False, default=False, verbose_name='一般ユーザフラグ')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', db_comment='管理者フラグ', db_default=False, default=False, verbose_name='管理者フラグ')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('groups', models.ManyToManyField(blank=True, related_name='group_m_user_set', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions_m_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザーマスタ',
                'verbose_name_plural': 'ユーザーマスタ',
                'db_table': 'm_user',
                'db_table_comment': 'ユーザーマスタ',
            },
        ),
        migrations.CreateModel(
            name='T_LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('login_identifier', models.CharField(db_column='login_identifier', db_comment='ログイン試行識別子', max_length=255, verbose_name='ログイン試行識別子')),
                ('is_successful', models.BooleanField(db_column='is_successful', db_comment='成功フラグ', db_index=True, verbose_name='成功フラグ')),
                ('failure_reason', models.CharField(blank=True, choices=[('PASSWORD_MISMATCH', 'パスワード不一致'), ('LOCKED', 'アカウントロック中'), ('NOT_ACTIVATED', 'アカウント未有効化')], db_column='failure_reason', db_comment='ログイン失敗理由コード', max_length=50, null=True, verbose_name='ログイン失敗理由コード')),
                ('ip_address', models.CharField(blank=True, db_column='ip_address', db_comment='IPアドレス', help_text='クライアントのIPアドレス', max_length=45, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, db_column='user_agent', db_comment='ユーザーエージェント', help_text='クライアントのブラウザ/OS情報', null=True, verbose_name='ユーザーエージェント')),
            ],
            options={
                'verbose_name': 'ログイン履歴トラン',
                'verbose_name_plural': 'ログイン履歴トラン',
                'db_table': 't_login_history',
                'db_table_comment': 'ログイン履歴トラン',
            },
        ),
        migrations.CreateModel(
            name='T_UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('token_type', models.CharField(choices=[('AC', 'アカウント有効化'), ('PR', 'パスワードリセット'), ('EC', 'メールアドレス変更確認')], db_column='token_type', db_comment='トークン種別', max_length=2, verbose_name='トークン種別')),
                ('token_hash', models.CharField(db_column='token_hash', db_comment='トークンハッシュ（SHA256など）', max_length=64, verbose_name='トークンハッシュ（SHA256など）')),
                ('expired_at', models.DateTimeField(db_column='expired_at', db_comment='トークン有効期限', verbose_name='トークン有効期限')),
            ],
            options={
                'verbose_name': 'ユーザ発行トークントラン',
                'verbose_name_plural': 'ユーザ発行トークントラン',
                'db_table': 't_user_token',
                'db_table_comment': 'ユーザ発行トークントラン',
            },
        ),
        migrations.CreateModel(
            name='T_Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('user', models.OneToOneField(db_column='user_id', db_comment='ユーザマスタ', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_t_profile_set', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ')),
                ('user_id_display', models.CharField(db_column='user_id_display', db_comment='ユーザID', max_length=255, verbose_name='ユーザID')),
                ('display_name', models.CharField(blank=True, db_column='display_name', db_comment='表示名', max_length=255, null=True, verbose_name='表示名')),
                ('affiliation', models.TextField(blank=True, db_column='affiliation', db_comment='所属', null=True, verbose_name='所属')),
                ('bio', models.TextField(blank=True, db_column='bio', db_comment='自己紹介', null=True, verbose_name='自己紹介')),
                ('is_setup_completed', models.BooleanField(db_column='is_setup_completed', db_comment='初期設定完了フラグ', db_default=False, default=False, verbose_name='初期設定完了フラグ')),
                ('status_code', models.IntegerField(choices=[(10, 'アクティブ'), (30, '一時ロック'), (40, '永続凍結'), (99, '退会済み')], db_column='status_code', db_comment='ステータスコード', db_default=10, db_index=True, default=10, verbose_name='ステータスコード')),
                ('locked_until_at', models.DateTimeField(blank=True, db_column='locked_until_at', db_comment='ロック解除日時', null=True, verbose_name='ロック解除日時')),
            ],
            options={
                'verbose_name': 'プロフィールトラン',
                'verbose_name_plural': 'プロフィールトラン',
                'db_table': 't_profile',
                'db_table_comment': 'プロフィールトラン',
            },
        ),
        migrations.CreateModel(
            name='HistoricalM_User',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', db_comment='作成日時', editable=False, null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', db_comment='更新日時', editable=False, null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('email', models.EmailField(db_column='email', db_comment='メールアドレス', max_length=254, verbose_name='メールアドレス')),
                ('password', models.CharField(db_column='password', db_comment='パスワード', max_length=128, verbose_name='パスワード')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', db_comment='最終ログイン', null=True, verbose_name='最終ログイン')),
                ('is_active', models.BooleanField(db_column='is_active', db_comment='有効フラグ', db_default=False, default=False, verbose_name='有効フラグ')),
                ('is_staff', models.BooleanField(db_column='is_staff', db_comment='一般ユーザフラグ', db_default=False, default=False, verbose_name='一般ユーザフラグ')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', db_comment='管理者フラグ', db_default=False, default=False, verbose_name='管理者フラグ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'historical ユーザーマスタ',
                'verbose_name_plural': 'historical ユーザーマスタ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalT_Profile',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', db_comment='作成日時', editable=False, null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', db_comment='更新日時', editable=False, null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('user_id_display', models.CharField(db_column='user_id_display', db_comment='ユーザID', max_length=255, verbose_name='ユーザID')),
                ('display_name', models.CharField(blank=True, db_column='display_name', db_comment='表示名', max_length=255, null=True, verbose_name='表示名')),
                ('affiliation', models.TextField(blank=True, db_column='affiliation', db_comment='所属', null=True, verbose_name='所属')),
                ('bio', models.TextField(blank=True, db_column='bio', db_comment='自己紹介', null=True, verbose_name='自己紹介')),
                ('is_setup_completed', models.BooleanField(db_column='is_setup_completed', db_comment='初期設定完了フラグ', db_default=False, default=False, verbose_name='初期設定完了フラグ')),
                ('status_code', models.IntegerField(choices=[(10, 'アクティブ'), (30, '一時ロック'), (40, '永続凍結'), (99, '退会済み')], db_column='status_code', db_comment='ステータスコード', db_default=10, db_index=True, default=10, verbose_name='ステータスコード')),
                ('locked_until_at', models.DateTimeField(blank=True, db_column='locked_until_at', db_comment='ロック解除日時', null=True, verbose_name='ロック解除日時')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical プロフィールトラン',
                'verbose_name_plural': 'historical プロフィールトラン',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
