# Generated by Django 6.0.3 on 2026-04-26 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalt_profile',
            name='icon',
            field=models.ForeignKey(blank=True, db_column='icon_id', db_comment='アイコン', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.t_fileresource', verbose_name='アイコン'),
        ),
        migrations.AddField(
            model_name='historicalt_profile',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='historicalt_profile',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', db_comment='ユーザマスタ', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ'),
        ),
        migrations.AddField(
            model_name='t_loginhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='t_loginhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='t_loginhistory',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', db_comment='ユーザマスタ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_t_login_history_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ'),
        ),
        migrations.AddField(
            model_name='t_usertoken',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='t_usertoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='t_usertoken',
            name='user',
            field=models.ForeignKey(db_column='user_id', db_comment='ユーザマスタ', on_delete=django.db.models.deletion.CASCADE, related_name='user_t_user_token_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ'),
        ),
        migrations.AddField(
            model_name='t_profile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='t_profile',
            name='icon',
            field=models.ForeignKey(blank=True, db_column='icon_id', db_comment='アイコン', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon_t_profile_set', to='common.t_fileresource', verbose_name='アイコン'),
        ),
        migrations.AddField(
            model_name='t_profile',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddConstraint(
            model_name='m_user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email',), name='unique_m_user_email_active'),
        ),
        migrations.AddConstraint(
            model_name='t_usertoken',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('token_hash',), name='unique_t_user_token_token_hash_active'),
        ),
        migrations.AddConstraint(
            model_name='t_profile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user_id',), name='unique_t_profile_user_id_active'),
        ),
    ]
