# Generated by Django 6.0.3 on 2026-04-29 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalt_profile',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='t_profile',
            name='affiliation',
        ),
        migrations.AlterField(
            model_name='historicalt_profile',
            name='icon',
            field=models.TextField(blank=True, db_column='icon', db_comment='アイコン', max_length=255, null=True, verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='t_loginhistory',
            name='id',
            field=models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='t_profile',
            name='icon',
            field=models.ImageField(blank=True, db_column='icon', db_comment='アイコン', max_length=255, null=True, upload_to='profiles/icons/', verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='t_usertoken',
            name='id',
            field=models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
