# Generated by Django 6.0.3 on 2026-05-03 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_historicalt_profile_affiliation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='R_Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('followee', models.ForeignKey(db_column='followee_id', db_comment='フォロー実行者/ユーザマスタ', on_delete=django.db.models.deletion.CASCADE, related_name='followee_r_follow_set', to=settings.AUTH_USER_MODEL, verbose_name='フォロー実行者/ユーザマスタ')),
                ('follower', models.ForeignKey(db_column='follower_id', db_comment='フォロワー/ユーザマスタ', on_delete=django.db.models.deletion.CASCADE, related_name='follower_r_follow_set', to=settings.AUTH_USER_MODEL, verbose_name='フォロワー/ユーザマスタ')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'フォローリレーション',
                'verbose_name_plural': 'フォローリレーション',
                'db_table': 'r_follow',
                'db_table_comment': 'フォローリレーション',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('follower', 'followee'), name='unique_r_follow_follower_followee_active')],
            },
        ),
    ]
