# Generated by Django 6.0.3 on 2026-05-03 17:17

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_r_itemtag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_LogCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', db_comment='ログカテゴリ名', max_length=64, verbose_name='ログカテゴリ名')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='ユーザマスタ', on_delete=django.db.models.deletion.CASCADE, related_name='user_m_log_category_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ')),
            ],
            options={
                'verbose_name': 'ログカテゴリマスタ',
                'verbose_name_plural': 'ログカテゴリマスタ',
                'db_table': 'm_log_category',
                'db_table_comment': 'ログカテゴリマスタ',
            },
        ),
        migrations.CreateModel(
            name='M_LogTheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', db_comment='ログテーマ名', max_length=64, verbose_name='ログテーマ名')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='ユーザマスタ', on_delete=django.db.models.deletion.CASCADE, related_name='user_m_log_theme_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ')),
            ],
            options={
                'verbose_name': 'ログテーママスタ',
                'verbose_name_plural': 'ログテーママスタ',
                'db_table': 'm_log_theme',
                'db_table_comment': 'ログテーママスタ',
            },
        ),
        migrations.CreateModel(
            name='R_LogCommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('emoji', models.ForeignKey(db_column='emoji_id', db_comment='絵文字', on_delete=django.db.models.deletion.CASCADE, related_name='emoji_%(class)s_set', to='common.m_emoji', verbose_name='絵文字')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_comment='ユーザマスタ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ')),
            ],
            options={
                'verbose_name': 'ログコメントリアクションリレーション',
                'verbose_name_plural': 'ログコメントリアクションリレーション',
                'db_table': 'r_log_comment_reaction',
                'db_table_comment': 'ログコメントリアクションリレーション',
            },
        ),
        migrations.CreateModel(
            name='R_LogReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('emoji', models.ForeignKey(db_column='emoji_id', db_comment='絵文字', on_delete=django.db.models.deletion.CASCADE, related_name='emoji_%(class)s_set', to='common.m_emoji', verbose_name='絵文字')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_comment='ユーザマスタ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ')),
            ],
            options={
                'verbose_name': 'ログリアクションリレーション',
                'verbose_name_plural': 'ログリアクションリレーション',
                'db_table': 'r_log_reaction',
                'db_table_comment': 'ログリアクションリレーション',
            },
        ),
        migrations.CreateModel(
            name='T_Log',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date', db_comment='実施日', verbose_name='実施日')),
                ('duration', models.PositiveIntegerField(db_column='duration', db_comment='作業時間', verbose_name='作業時間')),
                ('content', models.TextField(blank=True, db_column='content', db_comment='内容', null=True, verbose_name='内容')),
                ('output_url', models.URLField(blank=True, db_column='output_url', db_comment='成果物URL', null=True, verbose_name='成果物URL')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('log_category', models.ForeignKey(blank=True, db_column='log_category_id', db_comment='ログカテゴリマスタ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_category_t_log_set', to='log.m_logcategory', verbose_name='ログカテゴリマスタ')),
                ('log_theme', models.ForeignKey(blank=True, db_column='log_theme_id', db_comment='ログテーママスタ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_theme_t_log_set', to='log.m_logtheme', verbose_name='ログテーママスタ')),
                ('reactions', models.ManyToManyField(db_comment='リアクション', related_name='reactions_t_log_set', through='log.R_LogReaction', through_fields=('log', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='リアクション')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='ユーザマスタ', on_delete=django.db.models.deletion.CASCADE, related_name='user_t_log_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ')),
            ],
            options={
                'verbose_name': 'ログトラン',
                'verbose_name_plural': 'ログトラン',
                'db_table': 't_log',
                'db_table_comment': 'ログトラン',
            },
        ),
        migrations.AddField(
            model_name='r_logreaction',
            name='log',
            field=models.ForeignKey(db_column='log_id', db_comment='ログトラン', on_delete=django.db.models.deletion.CASCADE, related_name='log_r_log_reaction_set', to='log.t_log', verbose_name='ログトラン'),
        ),
        migrations.CreateModel(
            name='R_LogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('order', models.IntegerField(db_column='order', db_comment='並び順', default=0, verbose_name='並び順')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('file_resource', models.ForeignKey(blank=True, db_column='file_resource_id', db_comment='ファイルリソース', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_resource_%(class)s_set', to='common.t_fileresource', verbose_name='ファイルリソース')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('log', models.ForeignKey(db_column='log_id', db_comment='ログトラン', on_delete=django.db.models.deletion.CASCADE, related_name='log_r_log_attachment_set', to='log.t_log', verbose_name='ログトラン')),
            ],
            options={
                'verbose_name': 'ログ添付ファイルリレーション',
                'verbose_name_plural': 'ログ添付ファイルリレーション',
                'db_table': 'r_log_attachment',
                'db_table_comment': 'ログ添付ファイルリレーション',
            },
        ),
        migrations.CreateModel(
            name='T_LogComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, db_column='content', db_comment='内容', null=True, verbose_name='内容')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('log', models.ForeignKey(db_column='log_id', db_comment='ログトラン', on_delete=django.db.models.deletion.CASCADE, related_name='log_t_log_comment_set', to='log.t_log', verbose_name='ログトラン')),
                ('reactions', models.ManyToManyField(db_comment='リアクション', related_name='reactions_t_log_comment_set', through='log.R_LogCommentReaction', through_fields=('log_comment', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='リアクション')),
                ('reply_to', models.ForeignKey(blank=True, db_column='reply_to_id', db_comment='返信先', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to_t_log_comment_set', to='log.t_logcomment', verbose_name='返信先')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'ログコメントトラン',
                'verbose_name_plural': 'ログコメントトラン',
                'db_table': 't_log_comment',
                'db_table_comment': 'ログコメントトラン',
            },
        ),
        migrations.AddField(
            model_name='r_logcommentreaction',
            name='log_comment',
            field=models.ForeignKey(db_column='log_comment_id', db_comment='ログコメントトラン', on_delete=django.db.models.deletion.CASCADE, related_name='log_r_log_comment_reaction_set', to='log.t_logcomment', verbose_name='ログコメントトラン'),
        ),
        migrations.CreateModel(
            name='R_LogCommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('order', models.IntegerField(db_column='order', db_comment='並び順', default=0, verbose_name='並び順')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('file_resource', models.ForeignKey(blank=True, db_column='file_resource_id', db_comment='ファイルリソース', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_resource_%(class)s_set', to='common.t_fileresource', verbose_name='ファイルリソース')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('log_comment', models.ForeignKey(db_column='log_comment_id', db_comment='ログコメントトラン', on_delete=django.db.models.deletion.CASCADE, related_name='log_r_log_comment_attachment_set', to='log.t_logcomment', verbose_name='ログコメントトラン')),
            ],
            options={
                'verbose_name': 'ログコメント添付ファイルリレーション',
                'verbose_name_plural': 'ログコメント添付ファイルリレーション',
                'db_table': 'r_log_comment_attachment',
                'db_table_comment': 'ログコメント添付ファイルリレーション',
            },
        ),
        migrations.CreateModel(
            name='HistoricalT_LogComment',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', db_comment='作成日時', editable=False, null=True, verbose_name='作成日時')),
                ('created_method', models.CharField(blank=True, db_column='created_method', db_comment='作成処理', max_length=128, null=True, verbose_name='作成処理')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', db_comment='更新日時', editable=False, null=True, verbose_name='更新日時')),
                ('updated_method', models.CharField(blank=True, db_column='updated_method', db_comment='更新処理', max_length=128, null=True, verbose_name='更新処理')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', db_comment='削除日時', db_default=None, default=None, null=True, verbose_name='削除日時')),
                ('id', models.UUIDField(db_column='id', db_comment='ID', db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, db_column='content', db_comment='内容', null=True, verbose_name='内容')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_comment='作成者', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_id', db_comment='更新者', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('log', models.ForeignKey(blank=True, db_column='log_id', db_comment='ログトラン', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.t_log', verbose_name='ログトラン')),
                ('reply_to', models.ForeignKey(blank=True, db_column='reply_to_id', db_comment='返信先', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.t_logcomment', verbose_name='返信先')),
            ],
            options={
                'verbose_name': 'historical ログコメントトラン',
                'verbose_name_plural': 'historical ログコメントトラン',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='m_logcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_m_log_category_name_active'),
        ),
        migrations.AddConstraint(
            model_name='m_logtheme',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_m_log_theme_name_active'),
        ),
        migrations.AddConstraint(
            model_name='r_logreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('log', 'user', 'emoji'), name='unique_r_log_reaction_log_user_emoji_active'),
        ),
        migrations.AddConstraint(
            model_name='r_logattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('log', 'file_resource'), name='unique_r_log_attachment_log_file_resource_active'),
        ),
        migrations.AddConstraint(
            model_name='r_logcommentreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('log_comment', 'user', 'emoji'), name='unique_r_log_comment_reaction_log_user_emoji_active'),
        ),
        migrations.AddConstraint(
            model_name='r_logcommentattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('log_comment', 'file_resource'), name='unique_r_log_comment_attachment_log_comment_file_resource_active'),
        ),
    ]
