# Generated by Django 6.0.3 on 2026-05-04 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalt_logcomment',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', db_comment='ユーザマスタ', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ'),
        ),
        migrations.AddField(
            model_name='t_logcomment',
            name='user',
            field=models.ForeignKey(db_column='user_id', db_comment='ユーザマスタ', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_t_log_comment_set', to=settings.AUTH_USER_MODEL, verbose_name='ユーザマスタ'),
            preserve_default=False,
        ),
    ]
